"""add transaction type and cost fields

Revision ID: 4fdf336ab51d
Revises: 
Create Date: 2025-12-22 14:58:37.115445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdf336ab51d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_items', 'cost_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column(
        'inventory_transactions',
        sa.Column(
            'transaction_type',
            sa.String(),
            nullable=False,
            server_default='adjustment'
        )
    )

    op.add_column(
        'inventory_transactions',
        sa.Column(
            'unit_cost_at_time',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column('inventory_transactions', sa.Column('supplier', sa.String(), nullable=True))
    op.alter_column('inventory_transactions', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_transactions', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('inventory_transactions', 'supplier')
    op.drop_column('inventory_transactions', 'unit_cost_at_time')
    op.drop_column('inventory_transactions', 'transaction_type')
    op.alter_column('inventory_items', 'cost_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
